### ISSUE TITLE
unable to run the backend

### ISSUE THREAD

**Issue by cateee69** [GiorgioBrux/nitro-sniper-dashboard#1]
the font end works fine but when attempting to run the backend i get this error:
```events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:777
    at Server.setupListenHandle [as _listen2] (net.js:1314:21)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.attach (/root/nitro-sniper-dashboard/node_modules/socket.io/dist/index.js:176:17)
    at Server.listen (/root/nitro-sniper-dashboard/node_modules/socket.io/dist/index.js:149:21)
    at Object.<anonymous> (/root/nitro-sniper-dashboard/src/log.js:7:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 777
 }

**Comment by GiorgioBrux** [comment]
Sorry, for some reason I didn't receive a notification and sadly missed this :(
Did you eventually solve this?

**Comment by cateee69** [comment]
i solved it i only had to change ports a little bit

**Comment by GiorgioBrux** [comment]
Perfect, feel free to open another issue if needed.
